#!/usr/bin/env bash
# One-command demo launcher for the Gemma 4 Good Hackathon.
#
# This script:
#   1. Starts Ollama with Gemma 4 E2B (pulls the model on first run)
#   2. Bootstraps a minimal .env pointing at the local Ollama endpoint
#   3. Launches the CloakBot WebUI (gateway on :8000, frontend on :5173)
#   4. Opens http://127.0.0.1:5173 in your browser
#
# Once it's up, drag docs/demo/demo_onboarding_memo.md into the Composer:
#   - 20 PII entities detected by the local Gemma 4 E2B kernel
#   - chunker-backed redaction (2 chunks at the default 6,000-char boundary)
#   - Click "Diff" to see the Local vs Remote side-by-side
#
# Prerequisites:
#   - Ollama installed:  curl -fsSL https://ollama.com/install.sh | sh
#   - uv installed:      curl -LsSf https://astral.sh/uv/install.sh | sh
#   - Python deps:       uv sync
#   - Frontend deps:     cd webui && npm install   (~349 MB node_modules)
#
# Env overrides:
#   OLLAMA_MODEL    Default: gemma4:e2b  (passed through to start_ollama.sh)
#   GATEWAY_PORT    Default: 8000        (WebUI gateway port)
#   FRONTEND_PORT   Default: 5173        (Vite dev port)
#   SKIP_OPEN       Set to 1 to skip auto-opening the browser

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

GATEWAY_PORT="${GATEWAY_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
OLLAMA_HOST="${OLLAMA_HOST:-127.0.0.1:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-gemma4:e2b}"

# Step 1 — local backend
echo "==> [1/3] Starting Ollama backend (model: ${OLLAMA_MODEL})"
OLLAMA_MODEL="$OLLAMA_MODEL" OLLAMA_HOST="$OLLAMA_HOST" \
    bash "$REPO_ROOT/scripts/start_ollama.sh"

# Step 2 — bootstrap .env if missing
if [[ ! -f .env ]]; then
    echo "==> [2/3] Creating .env pointed at local Ollama"
    cat > .env <<EOF
# Auto-generated by scripts/quickstart_demo.sh
# Same three GEMMA_* vars cover vLLM and Ollama — cloakbot uses one
# OpenAI-compatible client class regardless of who's serving.
GEMMA_BASE_URL=http://${OLLAMA_HOST}/v1
GEMMA_API_KEY=ollama
GEMMA_MODEL=${OLLAMA_MODEL}
EOF
else
    echo "==> [2/3] .env already exists — leaving it alone"
    echo "    (If you want the demo to use Ollama, ensure GEMMA_BASE_URL"
    echo "     points at http://${OLLAMA_HOST}/v1)"
fi

# Step 3 — WebUI (gateway + frontend; cloakbot CLI starts both)
echo "==> [3/3] Starting WebUI"
echo "    Gateway : http://127.0.0.1:${GATEWAY_PORT}"
echo "    Frontend: http://127.0.0.1:${FRONTEND_PORT}"
echo ""

# Open browser after a short delay so the frontend has time to come up
if [[ "${SKIP_OPEN:-0}" != "1" ]]; then
    (
        sleep 6
        url="http://127.0.0.1:${FRONTEND_PORT}"
        if command -v open >/dev/null 2>&1; then
            open "$url"
        elif command -v xdg-open >/dev/null 2>&1; then
            xdg-open "$url"
        fi
    ) &
fi

# Friendly pre-flight: the local Gemma 4 detector runs without any cloud
# key, but the chat model (default: claude-opus-4-5) does not. Warn once
# if no remote key is in env or .env so the first message doesn't 500.
has_remote_key=0
for var in ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY; do
    if [[ -n "${!var:-}" ]]; then has_remote_key=1; fi
done
if [[ "$has_remote_key" -eq 0 ]] && [[ -f .env ]]; then
    if grep -qE '^(ANTHROPIC_API_KEY|OPENAI_API_KEY|GEMINI_API_KEY)=.+' .env 2>/dev/null; then
        has_remote_key=1
    fi
fi
if [[ "$has_remote_key" -eq 0 ]]; then
    cat <<'WARN'

⚠️  Heads-up: the local Gemma 4 detector is configured, but the chat model
    still needs a remote-LLM API key. The WebUI will load fine, but your
    first message will fail until you set one of:

        ANTHROPIC_API_KEY=...   (default chat model: claude-opus-4-5)
        OPENAI_API_KEY=...
        GEMINI_API_KEY=...

    Add to .env, or run:  uv run cloakbot onboard --wizard

WARN
fi

cat <<EOF

╭───────────────────────────────────────────────────────────────╮
│  Demo flow                                                    │
│                                                               │
│  1. The browser opens to http://127.0.0.1:${FRONTEND_PORT}                │
│  2. Drag docs/demo/demo_onboarding_memo.md into the Composer  │
│  3. Ask "Summarize this memo for the leadership team"         │
│  4. Click 'Diff' on either bubble to see Local vs Remote      │
│                                                               │
│  Press Ctrl-C to stop the WebUI. Ollama keeps running in the  │
│  background; stop it with: pkill ollama                       │
╰───────────────────────────────────────────────────────────────╯

EOF

exec uv run python -m cloakbot webui \
    --port "$GATEWAY_PORT" \
    --frontend-port "$FRONTEND_PORT"
